const CONF = {
	dimensions: {
		backgroundColor: 'transparent',
		height: '100vh',
		width: '100vw',
	},
	layout: {
		rows: 1,
		columns: 3,
	},
	elements: [
		{
			task: 'loop',
			cssClasses: 'rounded',
			width: '50px',
			height: '50px',
			x: '40vw',
			y: '90vh',
		},
		{
			task: 'prev',
			cssClasses: 'rounded',
			width: '50px',
			height: '50px',
			x: '45vw',
			y: '90vh',
		},
		{
			task: 'rewind',
			cssClasses: 'rounded',
			width: '50px',
			height: '50px',
			x: '50vw',
			y: '90vh',
		},
		{
			task: 'play',
			cssClasses: 'rounded',
			width: '50px',
			height: '50px',
			x: '55vw',
			y: '90vh',
		},
		{
			task: 'pause',
			cssClasses: 'rounded',
			width: '50px',
			height: '50px',
			x: '60vw',
			y: '90vh',
		},
		{
			task: 'stop',
			cssClasses: 'rounded',
			width: '50px',
			height: '50px',
			x: '65vw',
			y: '90vh',
		},
		{
			task: 'forward',
			cssClasses: 'rounded',
			width: '50px',
			height: '50px',
			x: '70vw',
			y: '90vh',
		},
		{
			task: 'next',
			cssClasses: 'rounded',
			width: '50px',
			height: '50px',
			x: '75vw',
			y: '90vh',
		},

		{
			task: 'bar',
			cssClasses: '',
			width: '60vw',
			height: '50px',
			x: '30vw',
			y: '86vh',
		},
		{
			task: 'playlist',
			cssClasses: '',
			width: '60vw',
			height: '70vh',
			x: '20vw',
			y: '10vh',
		},
		{
			task: 'image',
			cssClasses: '',
			width: '15vh',
			height: '15vh',
			x: '20vw',
			y: '84vh',
		},
	],
};
export default CONF;
